pipeline {
     agent any

    tools {
        // Specify the Maven installation
        maven 'Maven'
    }
    stages {
        stage('Checkout') {
            steps {
                // Checkout source code from GitHub repository
                git branch: 'main', credentialsId: '479a7451-9583-4262-b166-f2793f53a438', url: 'https://github.com/vk23191/JenkinsTestingSpringBoot.git'
            }
        }

        stage('Build') {
            steps {
                // Build a Maven project (replace with your build tool and commands)
                sh 'mvn clean package'  // Assumes Maven is installed on the Jenkins agent
            }
        }

        stage('Test') {
            steps {
                // Run tests (if applicable)
                sh 'mvn test'
            }
        }

        stage('Deploy') {
            steps {
                // Deployment steps (e.g., deploying to a server)
                sh 'mvn deploy'
            }
        }
    }

    post {
        success {
            echo 'Pipeline succeeded! This can include additional notifications or steps upon success.'
        }
        failure {
            echo 'Pipeline failed! This can include cleanup or notifications upon failure.'
        }
    }
}
